var stockN
async function getData() {
    // if(!city){
    // }
    // city = document.querySelector('.me-2').value
    stockN = document.getElementById('stockName').value 
    apiurl1 = `https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=${stockN}&apikey=T7LHA4F7LBUKYZBC`

    // get the movie information
    console.log(`... getting data info for that company`)
    weatherWeekly = await fetch(apiurl1).then(r => r.json())
    console.log(`${weatherWeekly}`)

    // weatherWeekly["Time Series (Daily)"]["2021-02-01"]["1. open"]
    document.getElementById("dateOfOutput").innerText  =`Daily Prices (${weatherWeekly["Meta Data"]["3. Last Refreshed"]})`
    document.getElementById("lastRefreshed").innerText = `Company: ${weatherWeekly["Meta Data"]["2. Symbol"]} `
    document.getElementById("yesterdayHigh").innerText = `High: ${weatherWeekly["Time Series (Daily)"]["2021-02-01"]["2. high"]}`
    document.getElementById("yesterdayLow").innerText = `Low: ${weatherWeekly["Time Series (Daily)"]["2021-02-01"]["3. low"]}`
    document.getElementById("yesterdayClose").innerText = `Close: ${weatherWeekly["Time Series (Daily)"]["2021-02-01"]["4. close"]}`
    document.getElementById("yesterdayVolume").innerText = `Volume: ${weatherWeekly["Time Series (Daily)"]["2021-02-01"]["5. volume"]}`
}

var yearMonth
var dayyy
function getDateFormat(){
    yearMonth = moment().format("Y-MM");
    
    if ((moment().subtract(1, 'days')["_d"]["getDay"]())<10)
     {dayyy=`0${moment().subtract(1, 'days')["_d"]["getDay"]()}`}
    else{dayyy =`${moment().subtract(1, 'days')["_d"]["getDay"]()}`}
    yearMonth += `-${dayyy}`

}


var cardArticle
async function getArticles() {
    // if(!city){
    // }
    // city = document.querySelector('.me-2').value
    cardArticle =await fetch("https://bloomberg-market-and-financial-news.p.rapidapi.com/news/list-by-region?id=canada-home-v3", {
        "method": "GET",
        "headers": {
            "x-rapidapi-key": "91acb173aamshe3a7ddc6687c44dp1d40fbjsnf966ff909dce",
            "x-rapidapi-host": "bloomberg-market-and-financial-news.p.rapidapi.com"
        }
    }).then(r => r.json())
 
    console.log(`${cardArticle}`)
    for(var i =0 ; i <3 ; i++){

    document.getElementById(`title${i+1}`).innerText = cardArticle.modules[1].stories[i].title
    document.getElementById(`thumbNail${i+1}`).setAttribute("src", cardArticle.modules[1].stories[i].thumbnailImage)
    document.getElementById(`summary${i+1}`).innerHTML = cardArticle.modules[1].stories[i].autoGeneratedSummary
    }    
}
getArticles()